apiVersion: v1
kind: Service
metadata:
  name: svc-web
spec:
  selector:
    app: web
  ports:
    - name: http-nginx
      port: 8080
      targetPort: nginx
    - name: http-multitool
      port: 8081
      targetPort: multitool
