---
  - name: Installing tools
    yum:
      name:
        - ntp
        - python
        - tcpdump
        - wget
        - openssl
        - curl
        - git
      state: present
      update_cache: yes
