---
- name: Install Clickhouse
  hosts: clickhouse
  force_handlers: true
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Block :)
      block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
            mode: 0644
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
            mode: 0644
          with_items: "{{ clickhouse_packages }}"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
    - name: Generate clickhouse config
      become: true
      ansible.builtin.template:
        src: config.xml.j2
        dest: /etc/clickhouse-server/config.xml
        mode: 0644
    - name: Generate clickhouse users config
      become: true
      ansible.builtin.template:
        src: users.xml.j2
        dest: /etc/clickhouse-server/users.xml
        mode: 0644
      notify: Start clickhouse service
  tags:
    - clickhouse

- name: Create DB & User For Vector
  hosts: clickhouse
  tasks:
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
    - name: Create user for vector
      ansible.builtin.command: clickhouse-client -q "create user vector identified by '{{ vector_clickhouse_password }}';"
      register: create_user
      failed_when: create_user.rc != 0 and create_user.rc != 237
      changed_when: create_user.rc == 0
  tags:
    - clickhouse-db

- name: Install Vector
  hosts: vector
  handlers:
    - name: Start vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Block :)
      block:
        - name: Create user for vector
          ansible.builtin.user:
            name: vector
            shell: /sbin/nologin
            state: present
            create_home: true
        - name: Get vector distrib
          ansible.builtin.get_url:
            url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
            dest: "/home/vector/vector-{{ vector_version }}.tar.gz"
            mode: 0644
        - name: Create directory for vector
          ansible.builtin.file:
            path: /opt/vector
            state: directory
            owner: vector
            group: vector
            mode: 0755
        - name: Create directory for vector data
          ansible.builtin.file:
            path: /opt/vector/data
            state: directory
            owner: vector
            group: vector
            mode: 0755
        - name: Extract vector
          ansible.builtin.unarchive:
            src: "/home/vector/vector-{{ vector_version }}.tar.gz"
            dest: /opt/vector
            owner: vector
            group: vector
            extra_opts: [--strip-components=2]
            remote_src: true
        - name: Generate systemd unit for vector
          ansible.builtin.template:
            src: vector.service.j2
            dest: /etc/systemd/system/vector.service
            mode: 0644
        - name: Rendering vector config
          ansible.builtin.template:
            src: vector.yml.j2
            dest: "/opt/vector/config/vector.yml"
            owner: vector
            group: vector
            mode: '0664'
          notify: Start vector service
  become: true
  tags:
    - vector
