---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      service: web
  template:
    metadata:
      labels:
        app: frontend
        service: web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: nginx-port
          protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  template:
    metadata:
      labels:
        app: backend
        service: web
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: '8080'
        ports:
        - containerPort: 8080
          name: multitool-port
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    service: web
  ports:
    - name: nginx-port
      port: 80
      targetPort: nginx-port
    - name: multitool-port
      port: 8080
      targetPort: multitool-port
