ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'
Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "k8s-master0#{i}" do |node|
      node.vm.box = "ubuntu/focal64"
      node.vm.hostname = "k8s-master0#{i}"
      node.vm.network "public_network", bridge: "REDACTED"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
      end
      ssh_pub_key = File.readlines("C:/Users/user/.ssh/id_rsa.pub").first.strip
      node.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false
    end
  end
  (1..2).each do |i|
    config.vm.define "k8s-worker0#{i}" do |node|
      node.vm.box = "ubuntu/focal64"
      node.vm.hostname = "k8s-worker0#{i}"
      node.vm.network "public_network", bridge: "REDACTED"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
      end
      ssh_pub_key = File.readlines("C:/Users/user/.ssh/id_rsa.pub").first.strip
      node.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false
    end
  end
end
