---
apiVersion: v1
kind: Pod
metadata:
  name: pod-echoserver-default
  labels:
    app: echoserver
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
