---
vector_version: "0.27.0"

vector_config:
  data_dir: /opt/vector/data
  sources:
    logs:
      read_from: beginning
      type: file
      include:
        - /home/vector/logs/*.log
      ignore_older: 86400
  sinks:
    clickhouse:
      type: clickhouse
      auth:
        user: vector
        password: "{{ vector_clickhouse_password | string }}"
        strategy: basic
      inputs:
        - logs
      endpoint: http://{{ hostvars['clickhouse'].ansible_host }}:8123
      database: logs
      table: app_logs
      skip_unknown_fields: true
      compression: gzip
      encoding:
        timestamp_format: "unix"
