---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-web
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: nginx
          protocol: TCP
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: '8080'
        ports:
        - containerPort: 8080
          name: multitool
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: svc-web
spec:
  selector:
    app: web
  ports:
    - name: http-nginx
      port: 9001
      targetPort: nginx
    - name: http-multitool
      port: 9002
      targetPort: multitool